chore(cicd): fix if

diff --git a/.github/workflows/terraform-pr.yml b/.github/workflows/terraform-pr.yml
--- a/.github/workflows/terraform-pr.yml
+++ b/.github/workflows/terraform-pr.yml
@@ -21,7 +21,7 @@ jobs:
           exit 0
         fi
         openssl enc -aes-256-cbc -md sha512 -salt -in terraform.tfstate.enc -out terraform.tfstate -d -pass env:STATE_PASSWORD
-        if [ ! -f terraform.tfstate ]; then echo "Decryption failed"; exit 1; fi
+        if [ ! -f terraform.tfstate ]; then echo "Decryption failed"exit 1; fi
       env:
         STATE_PASSWORD: ${{ secrets.TF_STATE_SECRET }}
 
