fix(terraform): add state

diff --git a/.github/workflows/terraform-deploy.yml b/.github/workflows/terraform-deploy.yml
--- a/.github/workflows/terraform-deploy.yml
+++ b/.github/workflows/terraform-deploy.yml
@@ -25,6 +25,7 @@ jobs:
         fi
         openssl enc -aes-256-cbc -salt -in terraform.tfstate.enc -out terraform.tfstate -d -pass env:STATE_PASSWORD
         rm terraform.tfstate.enc
+        if [ ! -f terraform.tfstate ]; then; echo "Decryption failed"; exit 1; fi
       env:
         STATE_PASSWORD: ${{ secrets.TF_STATE_SECRET }}
 
diff --git a/.github/workflows/terraform-pr.yml b/.github/workflows/terraform-pr.yml
--- a/.github/workflows/terraform-pr.yml
+++ b/.github/workflows/terraform-pr.yml
@@ -21,6 +21,7 @@ jobs:
           exit 0
         fi
         openssl enc -aes-256-cbc -salt -in terraform.tfstate.enc -out terraform.tfstate -d -pass env:STATE_PASSWORD
+        if [ ! -f terraform.tfstate ]; then echo "Decryption failed"; exit 1; fi
       env:
         STATE_PASSWORD: ${{ secrets.TF_STATE_SECRET }}
 
@@ -42,7 +43,6 @@ jobs:
       with:
         tf_actions_subcommand: "validate"
         tf_actions_version: "latest"
-
 
     - name: Terraform - Plan
       uses: hashicorp/terraform-github-actions@v0.6.4
